# Generated by Django 5.0.6 on 2024-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfigurasi',
            name='nilai',
            field=models.FloatField(),
        ),
    ]
